// Barrel module for the Taskloom domain service layer.
//
// The implementation lives in cohesive domain modules under ./services/*.
// This file re-exports the full public API so existing imports from
// "./taskloom-services.js" continue to resolve unchanged.

export {
  INVITATION_EMAIL_JOB_TYPE,
  listPublicActivationSummaries,
  getPublicActivationSummary,
  applySessionCookie,
  clearSessionCookie,
  toSubject,
  httpError,
} from "./services/context.js";

export {
  register,
  registerAsync,
  login,
  loginAsync,
  logout,
  logoutAsync,
  restoreSession,
  restoreSessionAsync,
  getPrivateBootstrap,
  getActivationDetail,
  getSessionPayload,
  getSessionPayloadAsync,
  updateProfile,
  requireAuthenticatedContext,
  requireAuthenticatedContextAsync,
} from "./services/auth.js";

export {
  updateWorkspace,
  listWorkspaceMembers,
  createWorkspaceInvitation,
  acceptWorkspaceInvitation,
  resendWorkspaceInvitation,
  revokeWorkspaceInvitation,
  updateWorkspaceMemberRole,
  removeWorkspaceMember,
  getOnboarding,
  completeOnboardingStep,
  handleInvitationEmailJob,
} from "./services/workspace.js";

export {
  listWorkspaceActivities,
  listWorkspaceActivitiesAsync,
  getWorkspaceActivityDetail,
  getWorkspaceActivityDetailAsync,
} from "./services/activities.js";

export {
  listAgents,
  listAgentsAsync,
  getAgent,
  generateAgentDraftFromPrompt,
  generateAgentFromPromptAsync,
  getAgentAsync,
  createAgent,
  createAgentAsync,
  updateAgent,
  updateAgentAsync,
  archiveAgent,
  archiveAgentAsync,
  runAgent,
  generateAgentBuilderDraftAsync,
  approveAgentBuilderDraftAsync,
  buildAgentSampleInputs,
  listAgentTemplates,
  getIntegrationReadiness,
  getIntegrationReadinessAsync,
  createAgentFromTemplate,
  createAgentFromTemplateAsync,
  listProviders,
  listProvidersAsync,
  createProvider,
  createProviderAsync,
  updateProvider,
  updateProviderAsync,
  listAgentRuns,
  listAgentRunsAsync,
  getAgentRunDetail,
  getAgentRunDetailAsync,
  cancelAgentRun,
  cancelAgentRunAsync,
  recordRunAsPlaybook,
  recordRunAsPlaybookAsync,
  retryAgentRun,
  listWorkspaceEnvVarsForUser,
  listWorkspaceEnvVarsForUserAsync,
  createWorkspaceEnvVar,
  createWorkspaceEnvVarAsync,
  updateWorkspaceEnvVar,
  updateWorkspaceEnvVarAsync,
  deleteWorkspaceEnvVarById,
  deleteWorkspaceEnvVarByIdAsync,
  listReleaseHistory,
  listReleaseHistoryAsync,
} from "./services/agents.js";

export type {
  AgentDraftOptions,
  AgentDraftInput,
  AgentDraftPlanItem,
  AgentDraft,
  AgentDraftResult,
  AgentBuilderPromptInput,
  AgentBuilderDraft,
  AgentBuilderApproveInput,
  AgentBuilderApproveResult,
  IntegrationReadinessSummary,
  RunAgentInput,
  RunAgentToolApprovalPayload,
  RunAgentResult,
  AgentRunTraceSpanKind,
  AgentRunTraceSpanStatus,
  AgentRunTraceSpan,
  AgentRunTraceDetail,
  AgentRunDetail,
} from "./services/agents.js";
